# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

"foot" = "$"
"jellyfin" = "ï‰¬"
"rust" = "î¨"
"firefox" = "ï‰©"
"floorp" = "ï„»"
"chrome" = "ï‰¨"
"thunar" = "ï¼"
"yazi" = "ï¼"
"libreoffice calc" = "ïƒ"
"libreoffice writer" = "ïœ˜"
"libreoffice" = "ï£…"
"spotify" = "ï€"
"discord"="ï‡—"
"teams"="ğŸ—¨"
"mattermost"="ğŸ—¯"
"solanum"="â²"
"hx" = "ï„"
"lazygit" = "ï‡“"
"nvim" = "î˜«"
"ghostty" = "ï„ "

[other]
fallback_icon = "ğŸ¤¨"
deduplicate_icons = true
